-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-return-type-field.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX wlzl_label_searchindex;

DROP INDEX wlzl_label_searchindex_strict;

ALTER TABLE wikilambda_zobject_labels
  ADD wlzl_return_type TEXT DEFAULT NULL;

CREATE INDEX wlzl_label_searchindex ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label_normalised,
  wlzl_return_type
);

CREATE INDEX wlzl_label_searchindex_strict ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label,
  wlzl_return_type
);
