-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-aw_article_sections.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE aw_article_sections (
  awas_topic_qid TEXT NOT NULL,
  awas_section_qid TEXT NOT NULL,
  awas_locale TEXT NOT NULL,
  awas_schema_version SMALLINT NOT NULL,
  awas_payload TEXT NOT NULL,
  awas_last_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(
    awas_topic_qid, awas_section_qid,
  awas_locale, awas_schema_version
  )
);

CREATE UNIQUE INDEX awas_index_primary ON aw_article_sections (
  awas_topic_qid, awas_section_qid,
  awas_locale, awas_schema_version
);

CREATE INDEX awas_index_metadata ON aw_article_sections (
  awas_topic_qid, awas_section_qid,
	awas_schema_version
);
