-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_join.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilambda_zobject_join (
  wlzo_id BIGSERIAL NOT NULL,
  wlzo_main_zid TEXT NOT NULL,
  wlzo_main_type TEXT NOT NULL,
  wlzo_key TEXT NOT NULL,
  wlzo_related_zobject TEXT NOT NULL,
  wlzo_related_type TEXT NOT NULL,
  PRIMARY KEY(wlzo_id)
);

CREATE INDEX wlzo_index_main_zid_key ON wikilambda_zobject_join (wlzo_main_zid, wlzo_key);

CREATE INDEX wlzo_index_key_related_zobject ON wikilambda_zobject_join (wlzo_key, wlzo_related_zobject);
