-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zlanguages.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilambda_zlanguages (
  wlzlangs_id BIGSERIAL NOT NULL,
  wlzlangs_zid TEXT NOT NULL,
  wlzlangs_language TEXT NOT NULL,
  PRIMARY KEY(wlzlangs_id)
);
