-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_function_join.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilambda_zobject_function_join (
  wlzf_id BIGSERIAL NOT NULL,
  wlzf_ref_zid TEXT NOT NULL,
  wlzf_zfunction_zid TEXT NOT NULL,
  wlzf_type TEXT NOT NULL,
  PRIMARY KEY(wlzf_id)
);

CREATE INDEX wlzf_searchindex ON wikilambda_zobject_function_join (wlzf_type, wlzf_zfunction_zid);
