-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_label_conflicts.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilambda_zobject_label_conflicts (
  wlzlc_id BIGSERIAL NOT NULL,
  wlzlc_existing_zid TEXT NOT NULL,
  wlzlc_conflicting_zid TEXT NOT NULL,
  wlzlc_language TEXT NOT NULL,
  PRIMARY KEY(wlzlc_id)
);

CREATE INDEX wlzlc_searchindex ON wikilambda_zobject_label_conflicts (
  wlzlc_language, wlzlc_existing_zid
);
