-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikifunctionsclient_usage (
  wfcu_id BIGSERIAL NOT NULL,
  wfcu_targetFunction TEXT NOT NULL,
  wfcu_targetPage TEXT NOT NULL,
  PRIMARY KEY(wfcu_id)
);

CREATE UNIQUE INDEX wfcu_unique ON wikifunctionsclient_usage (
  wfcu_targetFunction, wfcu_targetPage
);
