-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_labels.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilambda_zobject_labels (
  wlzl_id BIGSERIAL NOT NULL,
  wlzl_zobject_zid TEXT NOT NULL,
  wlzl_type TEXT NOT NULL,
  wlzl_language TEXT NOT NULL,
  wlzl_label TEXT NOT NULL,
  wlzl_label_normalised TEXT NOT NULL,
  wlzl_label_primary SMALLINT DEFAULT 1 NOT NULL,
  wlzl_return_type TEXT DEFAULT NULL,
  PRIMARY KEY(wlzl_id)
);

CREATE INDEX wlzl_label_searchindex ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label_normalised,
  wlzl_return_type
);

CREATE INDEX wlzl_label_searchindex_strict ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label,
  wlzl_return_type
);

CREATE INDEX wlzl_searchindex_zid ON wikilambda_zobject_labels (wlzl_zobject_zid);

CREATE INDEX wlzl_searchindex_orderby_priority ON wikilambda_zobject_labels (
  wlzl_language, wlzl_label_primary
);
