-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-wikifunctions_usage_wikis.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikifunctions_usage_wikis (
  wfuw_id SERIAL NOT NULL,
  wfuw_wiki TEXT NOT NULL,
  wfuw_namespace_id INT NOT NULL,
  wfuw_namespace_text TEXT DEFAULT NULL,
  PRIMARY KEY(wfuw_id)
);

CREATE UNIQUE INDEX wfuw_wiki_namespace ON wikifunctions_usage_wikis (wfuw_wiki, wfuw_namespace_id);
