var Constants = {
	EXCLUDED_Z_TYPES: [ 'Z1', 'Z2', 'Z7', 'Z9' ],
	Z_OBJECT: 'Z1',
	Z_OBJECT_TYPE: 'Z1K1',
	Z_PERSISTENTOBJECT: 'Z2',
	Z_PERSISTENTOBJECT_ID: 'Z2K1',
	Z_PERSISTENTOBJECT_VALUE: 'Z2K2',
	Z_PERSISTENTOBJECT_LABEL: 'Z2K3',
	Z_KEY: 'Z3',
	Z_KEY_TYPE: 'Z3K1',
	Z_KEY_ID: 'Z3K2',
	Z_KEY_LABEL: 'Z3K3',
	Z_TYPE: 'Z4',
	Z_TYPE_KEYS: 'Z4K2',
	Z_STRING: 'Z6',
	Z_REFERENCE: 'Z9',
	Z_LIST: 'Z10',
	Z_MONOLINGUALSTRING: 'Z11',
	Z_MONOLINGUALSTRING_LANGUAGE: 'Z11K1',
	Z_MONOLINGUALSTRING_VALUE: 'Z11K2',
	Z_MULTILINGUALSTRING: 'Z12',
	Z_MULTILINGUALSTRING_VALUE: 'Z12K1'
};

module.exports = Constants;
