-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiLambda/includes/sql/table-zobject_labels.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilambda_zobject_labels (
  wlzl_id BIGSERIAL NOT NULL,
  wlzl_zobject_zid TEXT NOT NULL,
  wlzl_type TEXT NOT NULL,
  wlzl_language TEXT NOT NULL,
  wlzl_label TEXT NOT NULL,
  wlzl_label_normalised TEXT NOT NULL,
  PRIMARY KEY(wlzl_id)
);

CREATE INDEX wlzl_label_searchindex ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label_normalised
);

CREATE INDEX wlzl_label_searchindex_strict ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label
);

CREATE UNIQUE INDEX wlzl_label_unique ON wikilambda_zobject_labels (
  wlzl_type, wlzl_language, wlzl_label
);
