-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-zobject-labels-priority-index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__wikilambda_zobject_labels AS
SELECT
  wlzl_id,
  wlzl_zobject_zid,
  wlzl_type,
  wlzl_language,
  wlzl_label,
  wlzl_label_normalised,
  wlzl_label_primary,
  wlzl_return_type
FROM /*_*/wikilambda_zobject_labels;
DROP TABLE /*_*/wikilambda_zobject_labels;


CREATE TABLE /*_*/wikilambda_zobject_labels (
    wlzl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    wlzl_zobject_zid BLOB NOT NULL, wlzl_type BLOB NOT NULL,
    wlzl_language BLOB NOT NULL, wlzl_label BLOB NOT NULL,
    wlzl_label_normalised BLOB NOT NULL,
    wlzl_label_primary SMALLINT DEFAULT 1 NOT NULL,
    wlzl_return_type BLOB DEFAULT NULL
  );
INSERT INTO /*_*/wikilambda_zobject_labels (
    wlzl_id, wlzl_zobject_zid, wlzl_type,
    wlzl_language, wlzl_label, wlzl_label_normalised,
    wlzl_label_primary, wlzl_return_type
  )
SELECT
  wlzl_id,
  wlzl_zobject_zid,
  wlzl_type,
  wlzl_language,
  wlzl_label,
  wlzl_label_normalised,
  wlzl_label_primary,
  wlzl_return_type
FROM
  /*_*/__temp__wikilambda_zobject_labels;
DROP TABLE /*_*/__temp__wikilambda_zobject_labels;

CREATE INDEX wlzl_label_searchindex ON /*_*/wikilambda_zobject_labels (
    wlzl_type, wlzl_language, wlzl_label_normalised,
    wlzl_return_type
  );

CREATE INDEX wlzl_label_searchindex_strict ON /*_*/wikilambda_zobject_labels (
    wlzl_type, wlzl_language, wlzl_label,
    wlzl_return_type
  );

CREATE INDEX wlzl_searchindex_zid ON /*_*/wikilambda_zobject_labels (wlzl_zobject_zid);

CREATE INDEX wlzl_searchindex_orderby_priority ON /*_*/wikilambda_zobject_labels (
    wlzl_language, wlzl_label_primary
  );
