-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-zobject-join-type-index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__wikilambda_zobject_join AS
SELECT
  wlzo_id,
  wlzo_main_zid,
  wlzo_main_type,
  wlzo_key,
  wlzo_related_zobject,
  wlzo_related_type
FROM /*_*/wikilambda_zobject_join;
DROP TABLE /*_*/wikilambda_zobject_join;


CREATE TABLE /*_*/wikilambda_zobject_join (
    wlzo_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    wlzo_main_zid BLOB NOT NULL, wlzo_main_type BLOB NOT NULL,
    wlzo_key BLOB NOT NULL, wlzo_related_zobject BLOB NOT NULL,
    wlzo_related_type BLOB NOT NULL
  );
INSERT INTO /*_*/wikilambda_zobject_join (
    wlzo_id, wlzo_main_zid, wlzo_main_type,
    wlzo_key, wlzo_related_zobject,
    wlzo_related_type
  )
SELECT
  wlzo_id,
  wlzo_main_zid,
  wlzo_main_type,
  wlzo_key,
  wlzo_related_zobject,
  wlzo_related_type
FROM
  /*_*/__temp__wikilambda_zobject_join;
DROP TABLE /*_*/__temp__wikilambda_zobject_join;

CREATE INDEX wlzo_index_main_zid_key ON /*_*/wikilambda_zobject_join (wlzo_main_zid, wlzo_key);

CREATE INDEX wlzo_index_key_related_zobject ON /*_*/wikilambda_zobject_join (wlzo_key, wlzo_related_zobject);

CREATE INDEX wlzo_index_related_type ON /*_*/wikilambda_zobject_join (wlzo_related_type);
