-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-aw_article_sections.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aw_article_sections (
  awas_topic_qid BLOB NOT NULL,
  awas_section_qid BLOB NOT NULL,
  awas_locale BLOB NOT NULL,
  awas_schema_version SMALLINT UNSIGNED NOT NULL,
  awas_payload BLOB NOT NULL,
  awas_last_updated BLOB NOT NULL,
  PRIMARY KEY(
    awas_topic_qid, awas_section_qid,
    awas_locale, awas_schema_version
  )
);

CREATE UNIQUE INDEX awas_index_primary ON /*_*/aw_article_sections (
  awas_topic_qid, awas_section_qid,
  awas_locale, awas_schema_version
);

CREATE INDEX awas_index_metadata ON /*_*/aw_article_sections (
  awas_topic_qid, awas_section_qid,
	awas_schema_version
);
