-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-wikifunctions_usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifunctions_usage (
  wfu_function INTEGER UNSIGNED NOT NULL,
  wfu_wiki_id INTEGER UNSIGNED NOT NULL,
  wfu_page_id INTEGER UNSIGNED NOT NULL,
  wfu_title BLOB NOT NULL,
  PRIMARY KEY(
    wfu_function, wfu_wiki_id, wfu_page_id
  )
);

CREATE INDEX wfu_wiki_page ON /*_*/wikifunctions_usage (wfu_wiki_id, wfu_page_id);
