-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_function_join.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_function_join (
  wlzf_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wlzf_ref_zid BLOB NOT NULL, wlzf_zfunction_zid BLOB NOT NULL,
  wlzf_type BLOB NOT NULL
);

CREATE INDEX wlzf_searchindex ON /*_*/wikilambda_zobject_function_join (wlzf_type, wlzf_zfunction_zid);
