-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_join.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_join (
  wlzo_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wlzo_main_zid BLOB NOT NULL, wlzo_main_type BLOB NOT NULL,
  wlzo_key BLOB NOT NULL, wlzo_related_zobject BLOB NOT NULL,
  wlzo_related_type BLOB NOT NULL
);

CREATE INDEX wlzo_index_main_zid_key ON /*_*/wikilambda_zobject_join (wlzo_main_zid, wlzo_key);

CREATE INDEX wlzo_index_key_related_zobject ON /*_*/wikilambda_zobject_join (wlzo_key, wlzo_related_zobject);

CREATE INDEX wlzo_index_related_type ON /*_*/wikilambda_zobject_join (wlzo_related_type);
