-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_label_conflicts.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_label_conflicts (
  wlzlc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wlzlc_existing_zid BLOB NOT NULL,
  wlzlc_conflicting_zid BLOB NOT NULL,
  wlzlc_language BLOB NOT NULL
);

CREATE INDEX wlzlc_searchindex ON /*_*/wikilambda_zobject_label_conflicts (
  wlzlc_language, wlzlc_existing_zid
);
