-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifunctionsclient_usage (
  wfcu_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wfcu_targetFunction BLOB NOT NULL,
  wfcu_targetPage BLOB NOT NULL
);

CREATE UNIQUE INDEX wfcu_unique ON /*_*/wikifunctionsclient_usage (
  wfcu_targetFunction, wfcu_targetPage
);
