-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-wikifunctions_usage_wikis.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifunctions_usage_wikis (
  wfuw_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wfuw_wiki BLOB NOT NULL, wfuw_namespace_id INTEGER NOT NULL,
  wfuw_namespace_text BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX wfuw_wiki_namespace ON /*_*/wikifunctions_usage_wikis (wfuw_wiki, wfuw_namespace_id);
