-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-zobject-labels-zid-index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX wlzl_searchindex_zid ON /*_*/wikilambda_zobject_labels (wlzl_zobject_zid);
