-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-zobject-labels-priority-index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX wlzl_searchindex_orderby_priority ON /*_*/wikilambda_zobject_labels (
  wlzl_language, wlzl_label_primary
);
