-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-primary-label-field.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/wikilambda_zobject_labels
  ADD wlzl_label_primary TINYINT DEFAULT 1 NOT NULL;
