-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_function_join.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_function_join (
  wlzf_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wlzf_ref_zid VARBINARY(32) NOT NULL,
  wlzf_zfunction_zid VARBINARY(32) NOT NULL,
  wlzf_type VARBINARY(255) NOT NULL,
  INDEX wlzf_searchindex (wlzf_type, wlzf_zfunction_zid),
  PRIMARY KEY(wlzf_id)
) /*$wgDBTableOptions*/;
