-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-wikifunctions_usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifunctions_usage (
  wfu_function INT UNSIGNED NOT NULL,
  wfu_wiki_id INT UNSIGNED NOT NULL,
  wfu_page_id INT UNSIGNED NOT NULL,
  wfu_title VARBINARY(255) NOT NULL,
  INDEX wfu_wiki_page (wfu_wiki_id, wfu_page_id),
  PRIMARY KEY(
    wfu_function, wfu_wiki_id, wfu_page_id
  )
) /*$wgDBTableOptions*/;
