-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_join.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_join (
  wlzo_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wlzo_main_zid VARBINARY(32) NOT NULL,
  wlzo_main_type VARBINARY(255) NOT NULL,
  wlzo_key VARBINARY(32) NOT NULL,
  wlzo_related_zobject VARBINARY(255) NOT NULL,
  wlzo_related_type VARBINARY(255) NOT NULL,
  INDEX wlzo_index_main_zid_key (wlzo_main_zid, wlzo_key),
  INDEX wlzo_index_key_related_zobject (wlzo_key, wlzo_related_zobject),
  INDEX wlzo_index_related_type (wlzo_related_type),
  PRIMARY KEY(wlzo_id)
) /*$wgDBTableOptions*/;
