-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-usage.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifunctionsclient_usage (
  wfcu_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wfcu_targetFunction VARBINARY(32) NOT NULL,
  wfcu_targetPage VARBINARY(255) NOT NULL,
  UNIQUE INDEX wfcu_unique (
    wfcu_targetFunction, wfcu_targetPage
  ),
  PRIMARY KEY(wfcu_id)
) /*$wgDBTableOptions*/;
