-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zlanguages.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zlanguages (
  wlzlangs_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wlzlangs_zid VARBINARY(32) NOT NULL,
  wlzlangs_language VARBINARY(255) NOT NULL,
  PRIMARY KEY(wlzlangs_id)
) /*$wgDBTableOptions*/;
