-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-aw_article_sections.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aw_article_sections (
  awas_topic_qid VARBINARY(32) NOT NULL,
  awas_section_qid VARBINARY(64) NOT NULL,
  awas_locale VARBINARY(32) NOT NULL,
  awas_schema_version TINYINT UNSIGNED NOT NULL,
  awas_payload LONGBLOB NOT NULL,
  awas_last_updated BINARY(14) NOT NULL,
  UNIQUE INDEX awas_index_primary (
    awas_topic_qid, awas_section_qid,
    awas_locale, awas_schema_version
  ),
  INDEX awas_index_metadata (
    awas_topic_qid, awas_section_qid,
		awas_schema_version
  ),
  PRIMARY KEY(
    awas_topic_qid, awas_section_qid,
    awas_locale, awas_schema_version
  )
) /*$wgDBTableOptions*/;
