-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-wikifunctions_usage_wikis.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikifunctions_usage_wikis (
  wfuw_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  wfuw_wiki VARBINARY(64) NOT NULL,
  wfuw_namespace_id INT NOT NULL,
  wfuw_namespace_text VARBINARY(255) DEFAULT NULL,
  UNIQUE INDEX wfuw_wiki_namespace (wfuw_wiki, wfuw_namespace_id),
  PRIMARY KEY(wfuw_id)
) /*$wgDBTableOptions*/;
