-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_label_conflicts.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_label_conflicts (
  wlzlc_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wlzlc_existing_zid VARBINARY(32) NOT NULL,
  wlzlc_conflicting_zid VARBINARY(32) NOT NULL,
  wlzlc_language VARBINARY(255) NOT NULL,
  INDEX wlzlc_searchindex (
    wlzlc_language, wlzlc_existing_zid
  ),
  PRIMARY KEY(wlzlc_id)
) /*$wgDBTableOptions*/;
