-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/table-zobject_labels.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilambda_zobject_labels (
  wlzl_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  wlzl_zobject_zid VARBINARY(32) NOT NULL,
  wlzl_type VARBINARY(255) NOT NULL,
  wlzl_language VARBINARY(255) NOT NULL,
  wlzl_label VARBINARY(255) NOT NULL,
  wlzl_label_normalised VARBINARY(255) NOT NULL,
  wlzl_label_primary TINYINT DEFAULT 1 NOT NULL,
  wlzl_return_type VARBINARY(255) DEFAULT NULL,
  INDEX wlzl_label_searchindex (
    wlzl_type, wlzl_language, wlzl_label_normalised,
    wlzl_return_type
  ),
  INDEX wlzl_label_searchindex_strict (
    wlzl_type, wlzl_language, wlzl_label,
    wlzl_return_type
  ),
  PRIMARY KEY(wlzl_id)
) /*$wgDBTableOptions*/;
